#!/usr/bin/env python
"""Run VEP (Variant Effect Predictor) on prepared variant files.

This script runs Ensembl's VEP tool on single and multiple edit variant files
generated by prepare_variant_file_4_local_vep.py.
"""

import json
import subprocess
from pathlib import Path

import hydra
from omegaconf import DictConfig

# Get absolute path to config directory
CONFIG_DIR = Path(__file__).parent.parent.parent / "config"

# Number of header lines to skip in VEP output
# VEP_HEADER_LINES = 103
VEP_HEADER_LINES = 106


def run_vep_command(
    vep_venv_path: Path,
    dir_cache: Path,
    input_file: Path,
    output_file: Path,
    enst: str,
) -> None:
    """Run VEP on a single input file using conda environment.

    Args:
        vep_venv_path: Path to the conda/venv environment containing VEP.
        dir_cache: Path to the VEP cache directory.
        input_file: Path to the input variant file.
        output_file: Path for the VEP output file.
    """
    # Use conda run to execute VEP in the specific environment
    cmd = [
        "conda",
        "run",
        "-p",
        str(vep_venv_path),
        "--no-capture-output",
        "vep",
        "--offline",
        "--cache",
        "--dir_cache",
        str(dir_cache),
        "-i",
        str(input_file),
        "-o",
        str(output_file),
        "-v",
        "--everything",
        "--tab",
        "--transcript_filter",
        f"stable_id is {enst}",
    ]

    print(f"Running: {' '.join(cmd)}")
    subprocess.run(cmd, check=True)


def process_vep_output(vep_output_file: Path, final_output_file: Path) -> None:
    """Process VEP output by removing header lines.

    Args:
        vep_output_file: Path to the raw VEP output file.
        final_output_file: Path for the processed output file.
    """
    with open(vep_output_file, "r") as f_in:
        lines = f_in.readlines()

    # Skip header lines (equivalent to awk 'NR>=104')
    data_lines = lines[VEP_HEADER_LINES:]

    with open(final_output_file, "w") as f_out:
        f_out.writelines(data_lines)

    print(f"Processed output written to: {final_output_file}")


def run_vep_for_gene_editor(
    gene: str,
    editor: str,
    vep_venv_path: Path,
    dir_cache: Path,
    vep_data_dirpath: Path,
    enst: str,
) -> None:
    """Run VEP for a specific gene and editor combination.

    Args:
        gene: Gene name.
        editor: Editor type (ABE or CBE).
        vep_venv_path: Path to the conda/venv environment containing VEP.
        dir_cache: Path to the VEP cache directory.
        vep_data_dirpath: Directory containing input files and for output files.
    """
    for edit_type in ["single_edits", "multiple_edits"]:
        input_file = vep_data_dirpath / f"{edit_type}_{gene}_{editor}.csv"

        if not input_file.exists():
            print(f"Warning: {input_file} not found, skipping.")
            continue

        output_file = vep_data_dirpath / f"{edit_type}_{gene}_{editor}"
        final_output_file = vep_data_dirpath / f"{edit_type}_{gene}_{editor}_out.csv"

        print(f"Processing {edit_type} for {gene} with {editor}...")

        # Run VEP
        run_vep_command(
            vep_venv_path=vep_venv_path,
            dir_cache=dir_cache,
            input_file=input_file,
            output_file=output_file,
            enst=enst,
        )

        # Process output to remove headers
        process_vep_output(output_file, final_output_file)


@hydra.main(version_base=None, config_path=str(CONFIG_DIR), config_name="config")
def main(cfg: DictConfig) -> None:
    """Main entry point for running VEP."""
    target_genes = cfg.target_genes
    editors = cfg.editors
    vep_data_dirpath = Path(cfg.vep_data_dirpath)
    vep_venv_filepath = Path(cfg.vep_venv_filepath)
    vep_install_dirpath = Path(cfg.vep_install_filepath)
    gene2enst_filepath = Path(cfg.gene2enst_filepath)

    with open(gene2enst_filepath, "r") as f:
        gene2enst = json.load(f)

    # VEP cache directory
    dir_cache = vep_install_dirpath

    # Verify VEP environment exists
    if not vep_venv_filepath.exists():
        raise FileNotFoundError(
            f"VEP environment not found at {vep_venv_filepath}. "
            f"Please check vep_venv_filepath in config.yaml"
        )

    print(f"Using VEP environment: {vep_venv_filepath}")
    print(f"Using cache directory: {dir_cache}")
    print(f"Input/Output directory: {vep_data_dirpath}")

    for gene in target_genes:
        enst = gene2enst[gene]
        for editor in editors:
            run_vep_for_gene_editor(
                gene=gene,
                editor=editor,
                vep_venv_path=vep_venv_filepath,
                dir_cache=dir_cache,
                vep_data_dirpath=vep_data_dirpath,
                enst=enst,
            )

    print("VEP processing complete!")


if __name__ == "__main__":
    main()
